truncate table APM_VERTEX cascade;
truncate TABLE APM_METRIC_PATH cascade;
truncate TABLE APM_EDGE cascade;
truncate TABLE APM_VERTEX_LOGICAL_EQUIVALENCE cascade;
truncate table appmap_attribs cascade;
truncate table appmap_edges cascade;
truncate table appmap_id_mappings cascade;
truncate table appmap_model_vertices cascade;
truncate table appmap_vertices cascade;
